# Generated by Django 4.2.2 on 2023-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_carddetails_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=40)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
